### ISSUE TITLE
 zsh-notify: unsupported environment

### ISSUE THREAD

**Issue by OscarVelandia** [black7375/BlaCk-Void-Zsh#8]
Hi, after the last update, when I open a new terminal, appears the error  ```zsh-notify: unsupported environment``` 

This problem happens in WSL and KDE Neon.

Thanks

**Comment by black7375** [comment]
Are both errors?
It seems to be an error due to a missing package for `zsh-notify`.

Can you try install `xdotool`, `wmctl`??

**Comment by OscarVelandia** [comment]
When I try to install ```wmctl``` this error appear
```
E: Unable to locate package wmctl
                                                                                                                      
(eval):1: notify-if-background: function definition file not found
```

```xdotool``` was installed but the error persist.

**Comment by black7375** [comment]
Sorry, It's a spelling mistake. :sob: 
Please try again.

`wmctl` -> `wmctrl`

**Comment by OscarVelandia** [comment]
The problem is gone!, thank you,

**Comment by black7375** [comment]
Have a good day

**Comment by techbless** [comment]
I installed `wmctrl` and `xdotool`. but `zsh-notify: unsupported environment` keeps showing.
I am using WSL2

**Comment by black7375** [comment]
@techbless  I'll check this problem.

**Comment by psicho2000** [comment]
I am using WSL2, aswell. I looked a little bit around and found that an X11 server is necessary for xdo to run. My current Ubuntu setup is running without it, so `$DISPLAY` is empty and the notify plugin consequently fails.

I guess it could be fixed by installing X11 server and then forward it to Windows:
https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2/61110604#61110604

The other option is to just disable the notify plugin in `.zshrc`.

**Comment by patrick-dojofive** [comment]
I'm seeing this message, but only for the integrated terminal in VSCode

**Comment by black7375** [comment]
@patrick-dojofive I wrote a small fixing commit.
Try `zsh-update`.
